<?php

$this->inlineScript()
     ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js')
     ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery.payment/1.2.3/jquery.payment.min.js')
     ->appendFile('https://js.stripe.com/v2/')
     ->appendScript($this->stripeKey())
     ->appendFile('/js/card.js');

$this->headLink()->appendStylesheet('/css/card.css');
?>

<?= $this->render('tickets/ticket/_orderInformation', ['purchase' => $this->purchase]) ?>
<div class="row">
    <div class="col-md-6 col-xs-12">
        <?php $this->form->prepare();?>
        <form id="delegate-form" method="POST">
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading display-table" >
                    <div class="row display-tr" >
                        <h3 class="panel-title display-td" >Purchaser Information</h3>
                        <div class="display-td" ></div>
                    </div>
                </div>
                <div class="panel-body">
                    <?=$this->formHidden($this->form->get('stripe_token'));?>
                    <?=$this->formRow($this->form->get('purchase_email'));?>
                </div>
            </div>

            <?php for($i = 0; $i < $purchase->getTicketCount(); $i++):?>
                <div class="panel panel-default credit-card-box">
                    <div class="panel-heading display-table" >
                        <div class="row display-tr" >
                            <h3 class="panel-title display-td" >Delegate Information <?=$i+1?></h3>
                            <div class="display-td" ></div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <p class="help-block">You can complete this information later if you wish</p>
                        <?php echo $this->formCollection($this->form->get('delegates_' . $i));?>
                    </div>
                </div>
            <?php endfor;?>
            <?php echo $this->formHidden($this->form->get('security'))?>
        </form>
    </div>
    <div class="col-md-6 col-xs-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Payment Details</h3>
                    <div class="display-td" >
                        <img class="img-responsive pull-right" src="//img/accepted_c22e0.png">
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <?php if (!$this->noPayment):?>
                <form role="form" id="payment-form" method="POST" action="javascript:void(0);">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="cardNumber">Card number</label>
                                <div class="input-group">
                                    <input
                                            type="tel"
                                            class="form-control"
                                            name="cardNumber"
                                            placeholder="Valid Card Number"
                                            autocomplete="cc-number"
                                            required
                                    />
                                    <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-7 col-md-7">
                            <div class="form-group">
                                <label for="cardExpiry"><span class="hidden-xs">Expiration</span><span class="visible-xs-inline">Exp</span> Date</label>
                                <input
                                        type="tel"
                                        class="form-control"
                                        name="cardExpiry"
                                        placeholder="MM / YY"
                                        autocomplete="cc-exp"
                                        required
                                />
                            </div>
                        </div>
                        <div class="col-xs-5 col-md-5 pull-right">
                            <div class="form-group">
                                <label for="cardCVC">CVC</label>
                                <input
                                        type="tel"
                                        class="form-control"
                                        name="cardCVC"
                                        placeholder="CVC"
                                        autocomplete=false
                                        required
                                />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="cardName">Name on Card</label>
                                <input type="text" class="form-control" name="cardName" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="cardLine1">Address Line 1</label>
                                <input type="text" class="form-control" name="cardLine1" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="cardLine2">Address Line 2</label>
                                <input type="text" class="form-control" name="cardLine2" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="cardCity">City</label>
                                <input type="text" class="form-control" name="cardCity" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="cardState">County</label>
                                <input type="text" class="form-control" name="cardState" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="cardZip">Postcode</label>
                                <input type="text" class="form-control" name="cardZip" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="cardCountry">Country</label>
                                <input type="text" class="form-control" name="cardCountry" />
                            </div>
                        </div>
                    </div>
                    <div class="row" style="display:none;">
                        <div class="col-xs-12">
                            <p class="payment-errors"></p>
                        </div>
                    </div>
                </form>
                <?php else:?>
                    Payment details already provided
                <?php endif;?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group col-md-offset-10 col-md-2 col-xs-offset-6 col-xs-2">
        <button id="submit-payment" type="submit" class="btn btn-default">Complete Purchase</button>
    </div>
</div>
