<form class="form-horizontal" method="POST" action="">
    <table class="table">
    <?php foreach($this->tickets as $ticket):
    /** @var \OpenTickets\Tickets\Domain\ReadModel\TicketCounts\TicketCounter $ticket */
    ?>
        <tr>
            <td class="col-xs-9">
                <span class="col-xs-6">
                <?=$ticket->getTicketType()->getDisplayName()?>
                </span>
                <span class="col-xs-6">
                <?=$ticket->getRemaining()?> remaining
                </span>
            </td>
            <td class="col-xs-3">
                <span class="col-xs-6">
                £<?=$ticket->getTicketType()->getPrice()->getAmount()?> +VAT
                </span>
                <span class="col-xs-6">
                <input class="form-control" value="0" title="quantity" type="text" name="quantity[<?=$ticket->getId()?>]" />
                </span>
            </td>
        </tr>
    <?php endforeach;?>
    </table>
    <div class="col-xs-6"></div>
    <div class="form-group col-xs-6">
        <label for="discount_code" class="col-sm-4 control-label">Discount Code</label>
        <div class="col-sm-8">
            <input name="discount_code" type="text" class="form-control" id="discount_code" placeholder="Discount Code">
        </div>
    </div>
    <div class="col-xs-6"></div>
    <div class="form-group col-xs-6">
        <div class="col-sm-offset-9 col-sm-3">
            <button type="submit" class="btn btn-default">Continue</button>
        </div>
    </div>
</form>