<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Available tickets</h3>
                    <div class="display-td" ></div>
                </div>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="POST" action="">
                    <div class="row">
                        <div class="col-xs-12">
                        <table class="table">
                        <?php foreach($this->tickets as $ticket):
                        /** @var \OpenTickets\Tickets\Domain\ReadModel\TicketCounts\TicketCounter $ticket */
                        ?>
                            <tr>
                                <td class="col-md-9 col-xs-6">
                                    <span class="col-xs-12 col-md-6">
                                    <?=$ticket->getTicketType()->getDisplayName()?>
                                    </span>
                                    <span class="hidden-xs col-md-6">
                                    <?=$ticket->getRemaining()?> remaining
                                    </span>
                                </td>
                                <td class="col-md-3 col-xs-6">
                                    <span class="col-xs-6">
                                    <?=$this->moneyFormat($ticket->getTicketType()->getPrice())?>
                                    </span>
                                    <span class="col-xs-6">
                                    <input class="form-control" min="0" max="<?=$ticket->getRemaining()?>" value="0" title="quantity" type="number" name="quantity[<?=$ticket->getId()?>]" />
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="col-xs-offset-6 col-xs-6">
                                <div class="form-group">
                                <label for="discount_code" class="col-sm-4 control-label">Discount Code</label>
                                <div class="col-sm-8">
                                    <input name="discount_code" type="text" class="form-control" id="discount_code" placeholder="Discount Code" value="<?=$this->escapeHtmlAttr($this->discountCode)?>">
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <div class="col-md-12">
                                    <div class="col-md-offset-11 col-md-1 col-xs-1 col-xs-offset-8">
                                        <button type="submit" class="btn btn-default">Continue</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>